### ISSUE TITLE
Error: segment names may not start with erroneous periods clerk

### ISSUE THREAD

**Issue by SegevGanir** [adrianhajdin/threads#59]
Hi there! I'm currently at 25:46 at the video, and I'm getting this error in my terminal. 
Error: Segment names may not start with erroneous periods ('..sign-in').
    at UrlNode._insert (/workspace/threads/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:83:23)
    at UrlNode._insert (/workspace/threads/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:142:40)
    at UrlNode.insert (/workspace/threads/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:13:14)
    at /workspace/threads/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:165:46
    at Array.forEach (<anonymous>)
    at getSortedRoutes (/workspace/threads/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:165:21)
    at Watchpack.<anonymous> (/workspace/threads/node_modules/next/dist/server/lib/router-utils/setup-dev.js:860:65)

I don't know what I did wrong, and now I can't open up my page. 
My code is linked below. Please help!

https://github.com/SegevGanir/threads

**Comment by SegevGanir** [comment]
I actually found out I was using 2 periods instead of 3 in the names of my folder 😆

**Comment by tbranch227** [comment]
@SegevGanir I was using 4.  Nice catch that took me right to the problem.  I need new glasses lol
