### ISSUE TITLE
Cannot redefine property: bind

### ISSUE THREAD

**Issue by erfanazari** [adrianhajdin/threads#65]
- error node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-proxy.js (37:11) @ defineProperties
- error TypeError: Cannot redefine property: bind
    at Function.defineProperties (<anonymous>)
    at eval (./lib/models/thread.model.ts:43:81)
    at (actionBrowser)/./lib/models/thread.model.ts (/Users/erfan/Desktop/Nextjs/threads/.next/server/app/(root)/page.js:3319:1)
    at __webpack_require__ (/Users/erfan/Desktop/Nextjs/threads/.next/server/webpack-runtime.js:33:42)
    at eval (./lib/actions/thread.actions.ts:8:82)
    at (actionBrowser)/./lib/actions/thread.actions.ts (/Users/erfan/Desktop/Nextjs/threads/.next/server/app/(root)/page.js:3308:1)
    at Function.__webpack_require__ (/Users/erfan/Desktop/Nextjs/threads/.next/server/webpack-runtime.js:33:42)

Hi, i have this issues when i making the fetchPosts.
I need your help

**Comment by sXrg97** [comment]
me too

**Comment by Thomas-Shelby2** [comment]
did you find the solution?

**Comment by MohammedAslam106** [comment]
Does anyone know the solution?

It's so annoying.
![Threads_clone_Error](https://github.com/adrianhajdin/threads/assets/117932780/914d9ffa-3a85-4280-9570-7112bacea37d)

**Comment by jtaiwo09** [comment]
Were you able to find a solution to this error?

**Comment by kubabowski** [comment]
If anyone finds the solution, please write it here

**Comment by Eddie2111** [comment]
I found an annoying solution to this.
Remove the .next folder every time you make a change in the api's

Seem like it's is caching even the functions which is creating the problem in data binding.

I got so annoyed by it that I switched to Prisma.

**Comment by monitortomar** [comment]
Have the same issue.
But got rid off , by removing extra imported files or modules.
Thanks

**Comment by mikhael-dantas** [comment]
I found the reason for my specific next application to throw that error.

Seems that nextjs have soem problems of import/export for certain dependencies, so if ou for example import hashSync from bcrypt in a "use server" file, then exports a variable with it, and use it on a client side component or another file, next throws that error.

so basically, if every single file that is "use server" or imported from anything in the flow of server functions, these files should only export async functions, nothing more. So check your exports in the files.

For hashSync by example, I solved exporting a async function that runs hashSync inside it with the same arguments.
