### ISSUE TITLE
Error: Operation `threads.countDocuments()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by feihuan1** [adrianhajdin/threads#96]
this happens when i create community, it was ok last night and second day when i run dev, it shows the error

react-server-dom-webpack-client.browser.development.js:1168 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
redirect-boundary.js:60 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
not-found-boundary.js:24 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
redirect-boundary.js:60 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
not-found-boundary.js:24 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
redirect-boundary.js:60 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
not-found-boundary.js:24 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
react-server-dom-webpack-client.browser.development.js:1168 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
redirect-boundary.js:60 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
not-found-boundary.js:24 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
redirect-boundary.js:60 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
not-found-boundary.js:24 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
redirect-boundary.js:60 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
not-found-boundary.js:24 Uncaught MongooseError: Operation `threads.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\ericr\OneDrive\Desktop\socialmedia\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:186:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
app-index.js:31 The above error occurred in the <NotFoundErrorBoundary> component:

    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/dev-root-not-found-boundary.js:32:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:294:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:157:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:82:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:110:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:440:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:126:11)
    at RSCComponent
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:142:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)

React will try to recreate this component tree from scratch using the error boundary you provided, ReactDevOverlay.
window.console.error @ app-index.js:31
8The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by d-erfliw** [comment]
at MONGODB_URL put your actual password replacing the <password> tag

**Comment by feihuan1** [comment]
😂I wasn't able to read error message at that time
